/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.zombito.exporter.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param completed 
 * @param panicSold 
 * @param active 
 * @param completedDealsUsdProfit 
 * @param fromCurrencyIsDollars 
 * @param completedDealsBtcProfit 
 * @param fundsLockedInActiveDeals 
 * @param btcFundsLockedInActiveDeals 
 * @param activeDealsUsdProfit 
 * @param activeDealsBtcProfit 
 */


data class BotDealsStatsEntity (

    @field:JsonProperty("completed")
    val completed: kotlin.Int? = null,

    @field:JsonProperty("panic_sold")
    val panicSold: kotlin.Int? = null,

    @field:JsonProperty("active")
    val active: kotlin.Int? = null,

    @field:JsonProperty("completed_deals_usd_profit")
    val completedDealsUsdProfit: kotlin.String? = null,

    @field:JsonProperty("from_currency_is_dollars")
    val fromCurrencyIsDollars: kotlin.Boolean? = null,

    @field:JsonProperty("completed_deals_btc_profit")
    val completedDealsBtcProfit: kotlin.String? = null,

    @field:JsonProperty("funds_locked_in_active_deals")
    val fundsLockedInActiveDeals: kotlin.String? = null,

    @field:JsonProperty("btc_funds_locked_in_active_deals")
    val btcFundsLockedInActiveDeals: kotlin.String? = null,

    @field:JsonProperty("active_deals_usd_profit")
    val activeDealsUsdProfit: kotlin.String? = null,

    @field:JsonProperty("active_deals_btc_profit")
    val activeDealsBtcProfit: kotlin.String? = null

)

