/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.zombito.exporter.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Values: [\"Bot::MultiBot\", \"Bot::SingleBot\", \"Bot::SwitchBot\"]
 *
 * Values: multiBot,singleBot,switchBot
 */

enum class BotType(val value: kotlin.String) {

    @JsonProperty(value = "Bot::MultiBot")
    multiBot("Bot::MultiBot"),

    @JsonProperty(value = "Bot::SingleBot")
    singleBot("Bot::SingleBot"),

    @JsonProperty(value = "Bot::SwitchBot")
    switchBot("Bot::SwitchBot");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is BotType) "$data" else null

        /**
         * Returns a valid [BotType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): BotType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

