/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.zombito.exporter.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Values: stop_loss, stop_loss_and_disable_bot
 *
 * Values: loss,lossAndDisableBot
 */

enum class StopLossType(val value: kotlin.String) {

    @JsonProperty(value = "stop_loss")
    loss("stop_loss"),

    @JsonProperty(value = "stop_loss_and_disable_bot")
    lossAndDisableBot("stop_loss_and_disable_bot");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is StopLossType) "$data" else null

        /**
         * Returns a valid [StopLossType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): StopLossType? = data?.let {
            val normalizedData = "$it".lowercase()
            values().firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}

